name: auth
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - sqlalchemy=1.4.46
  - click
  - daiquiri
  - fastapi
  - ldap3
  - libiconv
  - oauthlib
  - pendulum
  - pycryptodome
  - pynacl
  - pytest
  - requests
  - sqlite
  - urllib3
  - uvicorn
