name: auth
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - sqlalchemy
  - click
  - cryptography
  - daiquiri
  - fastapi
  - filelock
  - gunicorn
  - ldap3
  - libiconv
  - pendulum
  - pillow
  - psycopg
  - pycryptodome
  - pyjwt
  - pynacl
  - pytest
  - pytest-asyncio
  - requests
  - sqlite
  - urllib3
  - uvicorn
  - lxml
