name: auth
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - sqlalchemy=1.4.46
  - click
  - cryptography
  - daiquiri
  - fastapi
  - gunicorn
  - ldap3
  - libiconv
  - pendulum
  - pillow
  - psycopg2
  - pycryptodome
  - pyjwt
  - pynacl
  - pytest
  - requests
  - sqlite
  - urllib3
  - uvicorn
