[project]
authors = ["Mark Servilla <mark.servilla@gmail.com>"]
channels = ["conda-forge"]
name = "auth"
platforms = ["linux-64", "linux-aarch64"]

[tasks]

[dependencies]
click = ">=8.1.8,<9"
daiquiri = ">=3.0.0,<4"
python = "3.11.*"
cryptography = ">=44.0.2,<45"
fastapi = ">=0.115.11,<0.116"
gunicorn = ">=23.0.0,<24"
ldap3 = ">=2.9.1,<3"
libiconv = ">=1.18,<2"
pendulum = ">=3.0.0,<4"
pillow = ">=11.1.0,<12"
pycryptodome = ">=3.22.0,<4"
pyjwt = ">=2.10.1,<3"
requests = ">=2.32.3,<3"
sqlite = ">=3.49.1,<4"
thefuzz = ">=0.22.1,<0.23"
urllib3 = ">=2.3.0,<3"
uvicorn = ">=0.34.0,<0.35"

[environments]
test = ["test"]

[feature.test.dependencies]
pytest = "*"
pylint = "*"
black = "*"

[feature.test.tasks]
test = "pytest"
