[tool.black]
skip-string-normalization = true

[tool.pytest.ini_options]
pythonpath = ["webapp"]

#filterwarnings = [
#    "error",
#    "ignore::sqlalchemy.esc.SAWarning",
#    # note the use of single quote below to denote "raw" strings in TOML
#    'ignore:function ham\(\) is deprecated:DeprecationWarning',
#]

#addopts = [
#    "-p no:warnings]"
#]

