@startuml
actor client
participant Gatekeeper
participant PASTA

title Authentication token REQUEST directly to Gatekeeper

autonumber

client->Gatekeeper: REQUEST with external auth-token
Gatekeeper->Gatekeeper: validate external auth-token
Gatekeeper->Gatekeeper: generate internal auth-token
Gatekeeper->PASTA: REQUEST internal auth-token
PASTA->PASTA: authorize service
PASTA->PASTA: authorize resource
PASTA->PASTA: execute service
Gatekeeper<--PASTA: RESPONSE
Gatekeeper->Gatekeeper: wrap external auth-token
client<--Gatekeeper: RESPONSE with external auth-token

@enduml