@startuml
skinparam sequenceMessageAlign center
actor client
participant ezEML
participant auth

client -> ezEML: newEML('xyz')\nEDI-XYZ
ezEML -> auth: create_resource('xyz')\nEDI-XYZ
activate auth
auth -> auth: is_authorized('EDI-XYZ',\n'create_resource',\n'write')
auth -> auth: create_resource('xyz')
auth -> auth: create_rule('EDI-XYZ', 'xyz',\n'changePermission')
auth -> ezEML: 200 OK
deactivate auth
@enduml